### ISSUE TITLE
Make paths to images relative to detect.py location

### ISSUE THREAD

**Issue by zaettar** [LucasVandroux/PyTorch-Rocket-YOLOv3-RetinaNet-SSD#6]
Would be nice to have the paths of the images loaded in the script be relative to the location of detect.py rather than relative to where the `python detect.py` is executed from. Would make using the script in Colab simpler.

**Comment by LucasVandroux** [comment]
This is just a tutorial that is destined to be as simple as possible to not confuse the users. Therefore, it is better to have as short and understandable pieces of code.

Moreover, this tutorial shouldn't be used for other purposes that the one it was used for.
